/**
 * tz.js — the timezone adapter.
 *
 * Everything the parser needs from a timezone database goes through these four functions. The
 * design intent (NATIVE_APP_PLAN.md, and the correction to it in CLAUDE.md) is that the parser
 * never touches a tz library directly: on the web and in the JavaScriptCore shell that is `Intl`,
 * and if a React Native engine ships without ICU data the fix is to swap this file for one backed
 * by a bundled tz library. Nothing above it changes.
 *
 * Semantics are Python's `zoneinfo`, because that is what the goldens were produced with:
 *   - UTC -> local is unambiguous and `Intl` answers it directly.
 *   - local wall time -> UTC follows PEP 495 with fold=0: in an ambiguous hour (fall back) the
 *     FIRST occurrence wins; in a nonexistent hour (spring forward) the offset in force BEFORE the
 *     transition is applied. `goldens/tz_vectors.json` — generated by Python — pins both.
 *
 * Instants are epoch milliseconds. Every instant the Trip Board produces is a whole minute.
 */

const MINUTE = 60_000;
const HOUR = 3_600_000;
const DAY = 86_400_000;

// Intl weekday names -> Python weekday() (Monday = 0 … Sunday = 6).
const WEEKDAY_INDEX = { Mon: 0, Tue: 1, Wed: 2, Thu: 3, Fri: 4, Sat: 5, Sun: 6 };
// Python's strftime("%a").upper()[:2], indexed by weekday().
export const WEEKDAY_CODES = ["MO", "TU", "WE", "TH", "FR", "SA", "SU"];

const formatters = new Map();

function formatter(tz) {
  let cached = formatters.get(tz);
  if (!cached) {
    // Throws RangeError for an unknown zone, which is the right behaviour: an invalid IANA name is
    // a programming error or a bad override, and zoneinfo raises for it too.
    cached = new Intl.DateTimeFormat("en-US", {
      timeZone: tz,
      hourCycle: "h23",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      weekday: "short",
    });
    formatters.set(tz, cached);
  }
  return cached;
}

/** Wall-clock fields of a UTC instant in `tz`. */
export function localParts(tz, ms) {
  const fields = {};
  for (const part of formatter(tz).formatToParts(new Date(ms))) fields[part.type] = part.value;
  return {
    year: Number(fields.year),
    month: Number(fields.month),
    day: Number(fields.day),
    hour: Number(fields.hour) % 24,          // belt and braces against a "24" at midnight
    minute: Number(fields.minute),
    second: Number(fields.second),
    weekday: WEEKDAY_INDEX[fields.weekday],
  };
}

/** Python's `utcoffset()` at a UTC instant, in minutes. */
export function utcOffsetMinutes(tz, ms) {
  const p = localParts(tz, ms);
  const asIfUtc = Date.UTC(p.year, p.month - 1, p.day, p.hour, p.minute, p.second);
  return Math.round((asIfUtc - ms) / MINUTE);
}

/** `datetime.astimezone(tz).strftime("%Y-%m-%dT%H:%M:%S")` — the naive local string. */
export function fmtLocal(tz, ms) {
  const p = localParts(tz, ms);
  const pad = (n) => String(n).padStart(2, "0");
  return `${String(p.year).padStart(4, "0")}-${pad(p.month)}-${pad(p.day)}` +
    `T${pad(p.hour)}:${pad(p.minute)}:${pad(p.second)}`;
}

/**
 * Local wall time in `tz` -> UTC instant, with zoneinfo's fold=0 semantics (see file comment).
 * `month` is 1-based, matching Python.
 */
export function localToUtc(tz, year, month, day, hour = 0, minute = 0) {
  const wall = Date.UTC(year, month - 1, day, hour, minute);

  // Offsets in force around this wall time bound the candidates; a zone changes offset at most
  // once in any 24 h window that matters here.
  const candidateOffsets = new Set([
    utcOffsetMinutes(tz, wall - DAY),
    utcOffsetMinutes(tz, wall),
    utcOffsetMinutes(tz, wall + DAY),
  ]);

  const valid = [];
  for (const offset of candidateOffsets) {
    const utc = wall - offset * MINUTE;
    if (utcOffsetMinutes(tz, utc) === offset) valid.push(utc);
  }
  // Unambiguous: one candidate. Ambiguous (fall back): fold=0 is the first occurrence, which is
  // the earlier instant.
  if (valid.length) return Math.min(...valid);

  // Nonexistent (spring forward): apply the offset in force just before the transition.
  const earliest = Math.min(...[...candidateOffsets].map((offset) => wall - offset * MINUTE));
  return wall - utcOffsetMinutes(tz, earliest) * MINUTE;
}

/** "2026-08-04T05:00:00Z" -> epoch ms. Throws on anything unreadable. */
export function parseUtc(iso) {
  const ms = Date.parse(iso);
  if (Number.isNaN(ms)) throw new RangeError(`Unreadable timestamp: ${iso}`);
  return ms;
}

/** epoch ms -> "2026-08-04T05:00:00Z", matching Python's strftime("%Y-%m-%dT%H:%M:%SZ"). */
export function fmtUtc(ms) {
  const d = new Date(ms);
  const p = (n, w = 2) => String(n).padStart(w, "0");
  return (
    `${p(d.getUTCFullYear(), 4)}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())}` +
    `T${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}Z`
  );
}

/** Calendar arithmetic on a (year, month, day) triple — Python's `date + timedelta(days=n)`. */
export function addDays({ year, month, day }, days) {
  const d = new Date(Date.UTC(year, month - 1, day + days));
  return { year: d.getUTCFullYear(), month: d.getUTCMonth() + 1, day: d.getUTCDate() };
}

export { MINUTE, HOUR, DAY };
